// <auto-generated />
using System;
using Game_Store.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Game_Store.Migrations
{
    [DbContext(typeof(GameContext))]
    partial class GameContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Game_Store.Models.Game", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GameId"), 1L, 1);

                    b.Property<double?>("Cost")
                        .IsRequired()
                        .HasColumnType("float");

                    b.Property<int?>("Rating")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Year")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("GameId");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            GameId = 1,
                            Cost = 49.990000000000002,
                            Rating = 9,
                            Title = "Final Fantasy XVI",
                            Year = 2023
                        },
                        new
                        {
                            GameId = 2,
                            Cost = 39.990000000000002,
                            Rating = 10,
                            Title = "Red Dead Redemption 2",
                            Year = 2018
                        },
                        new
                        {
                            GameId = 3,
                            Cost = 59.990000000000002,
                            Rating = 10,
                            Title = "Baldurs Gate 3",
                            Year = 2023
                        },
                        new
                        {
                            GameId = 4,
                            Cost = 19.989999999999998,
                            Rating = 9,
                            Title = "God of War (2018)",
                            Year = 2018
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
